# services:
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#       - '--storage.tsdb.path=/prometheus'
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#       - prometheus-data:/prometheus
#     ports:
#       - "9090:9090"
#     restart: unless-stopped

# volumes:
#   prometheus-data:
# services:
#   minio:
#     image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
#     container_name: minio
#     restart: unless-stopped
#     ports:
#       - "7030:9000"   # S3 API
#       - "6008:9001"   # Console
#     environment:
#       MINIO_ROOT_USER: miniopsg
#       MINIO_ROOT_PASSWORD: maruthi-suzuki
#     volumes:
#       - minio-data:/data
#     command: server /data --console-address ":9001"

# volumes:
#   minio-data:

version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: umami-postgres
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db:/var/lib/postgresql/data
    restart: unless-stopped

  umami:
    image: umamisoftware/umami:postgresql-latest
    container_name: umami
    ports:
      - "6004:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@postgres:5432/umami
      APP_SECRET: my-super-secret-key
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  umami-db:
