services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
    container_name: minio
    restart: unless-stopped
    ports:
      - "7030:9000"   # S3 API
      - "6005:9001"   # Console
    environment:
      MINIO_ROOT_USER: miniopsg
      MINIO_ROOT_PASSWORD: maruthi-suzuki
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
